name: Test building Docker image on PR

on:
  pull_request:
    types: [opened]

jobs:
  build:
    name: Build Docker image on supported architectures
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Only build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: srt-whep:build
